CREATE TABLE IF NOT EXISTS images (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub VARCHAR(255) NOT NULL,
    uuid_filename VARCHAR(36) NOT NULL UNIQUE,
    image_name VARCHAR(40) NOT NULL,
    image_description VARCHAR(120) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_images_sub 
        FOREIGN KEY (sub) 
        REFERENCES registered_user(sub)
        ON DELETE CASCADE
);

-- Create index on sub for better query performance
CREATE INDEX idx_images_sub ON images(sub);
